#!/usr/bin/env bash
# cambia las ips
#permisos de ejecucion
sleep 3

sudo sed -i 's/^127.0.0.1\s\+localhost/127.0.0.2 localhost/' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
