#!/usr/bin/env bash
# cambia las ips
#permisos de ejecucion
sleep 3

if grep -q "^127.0.0.1" /etc/hosts; then
    sudo sed -i 's/^127.0.0.1\s\+localhost/127.0.0.2 localhost/' /etc/hosts
else
    echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
fi
sudo sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
